export const DEFAULT_SETTINGS = {
  id: 'system_settings',
  hotelName: 'Mount Ash Villa',
  phone: '+94 52 222 3456',
  address: 'No. 24, Ash Mount Road, Nuwara Eliya, Sri Lanka',
  currency: 'Rs.',
  serviceChargePercent: 10,
  vatPercent: 0,
  allowReceptionistDelete: false,
  allowReceptionistDiscount: false,
  allowReceptionistModifyPrice: false,
  allowManagerSalaryChange: false,
  allowManagerUserEdit: true,
  allowReceptionistAddFoods: false,
  allowReceptionistEditFoods: false,
  allowReceptionistDeleteFoods: false,
  allowReceptionistManageGuests: true,
  allowReceptionistAddExpenses: false,
  allowReceptionistAddRooms: false,
  allowReceptionistEditRooms: false,
  allowReceptionistDeleteRooms: false,
  allowManagerManageRooms: true,
  allowManagerAddRooms: true,
  allowManagerEditRooms: true,
  allowManagerDeleteRooms: true,
  allowManagerAddFoods: true,
  allowManagerEditFoods: true,
  allowManagerDeleteFoods: true,
  allowManagerViewReports: true,
  allowManagerDeleteExpenses: false,
  taxNumber: '',
  email: 'reservations@grandpalace.com',
  checkInTime: '14:00',
  checkOutTime: '12:00',
  receiptFooterMessage: 'Thank you for staying with us! Please visit again.',
  printerType: 'thermal',
  paperWidth: '80mm',
  printerConnection: 'browser',
  printerIpAddress: '192.168.1.100',
  autoPrintOnSettle: false,
  showLogoOnReceipt: true,
  showTaxDetails: true,
};
