import type { SystemSettings } from '@/lib/types';

export const DEFAULT_SETTINGS: SystemSettings = {
  hotelName: 'Hotel POS System',
  phone: '+94 77 123 4567',
  address: 'Colombo, Sri Lanka',
  currency: 'LKR',
  serviceChargePercent: 10,
  vatPercent: 0,
  allowReceptionistDelete: false,
  allowReceptionistDiscount: true,
  allowReceptionistModifyPrice: true,
  allowManagerSalaryChange: true,
  allowManagerUserEdit: true,
  allowReceptionistAddFoods: true,
  allowReceptionistEditFoods: true,
  allowReceptionistDeleteFoods: false,
  allowReceptionistManageGuests: true,
  allowReceptionistAddExpenses: true,
  allowReceptionistAddRooms: true,
  allowReceptionistEditRooms: true,
  allowReceptionistDeleteRooms: false,
  allowManagerManageRooms: true,
  allowManagerAddRooms: true,
  allowManagerEditRooms: true,
  allowManagerDeleteRooms: false,
  allowManagerAddFoods: true,
  allowManagerEditFoods: true,
  allowManagerDeleteFoods: false,
  allowManagerViewReports: true,
  allowManagerDeleteExpenses: false,
  taxNumber: '0000000000',
  email: 'hotel@example.com',
  checkInTime: '14:00',
  checkOutTime: '12:00',
  receiptFooterMessage: 'Thank you for staying with us!',
  printerType: 'thermal',
  paperWidth: '58mm',
  printerConnection: 'browser',
  printerIpAddress: '192.168.1.100',
  autoPrintOnSettle: false,
  showLogoOnReceipt: true,
  showTaxDetails: false,
};
